spring.application.name=lab8_20204205GTICS
spring.datasource.url=jdbc:mysql://localhost:3307/expidition_db
spring.datasource.username=root
spring.datasource.password=1234
server.port=8080
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always